services:
  - type: web
    name: greenstay-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_test.__main__:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_PATH
        value: /opt/render/project/src/database/greendb
      - key: OPENAI_API_KEY
        sync: false
